# Site settings
title: Joshua Zenn
email: wordman05@gmail.com
description: Technology, science, music, gaming and sometimes crudely drawn art.
baseurl: ""
url: "https://armmaster17.github.io" # the base hostname & protocol for your site
twitter_username: zennjos
github_username:  ARMmaster17
timezone: America/New_York

# Build settings
markdown: kramdown

# Permalink settings
permalink: /:year/:month/:day/:title/

# Hide future posts
future: false

# Explicitly specify theme file to make Jekyll happy
#theme: theme
