# Site settings
title: Joshua Zenn
email: wordman05@gmail.com
description: The ravings of a mad man, with a little bit of technology and science.
baseurl: ""
url: "https://armmaster17.github.io" # the base hostname & protocol for your site
twitter_username: jzenn
github_username:  ARMmaster17
timezone: America/New_York

# Build settings
markdown: kramdown
